2024-10-06 17:00:01,248 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-06 17:05:12,177 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-06 17:05:27,775 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-06 17:06:08,515 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-06 17:06:32,175 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-06 17:06:53,421 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-06 17:07:39,166 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-06 17:07:55,593 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-06 17:08:42,429 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-06 17:09:48,499 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-06 17:10:12,733 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 902, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-10-12 12:01:24,037 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-12 12:01:55,530 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\app\routes.py", line 89, in edit_profile
    current_user.username = form.username.vljde
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'StringField' object has no attribute 'vljde'
2024-10-12 12:05:49,574 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
2024-10-12 12:06:03,449 ERROR: Exception on /edit_profile [POST] [in C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\deadg\microblog\app\routes.py", line 89, in edit_profile
    current_user.username = form.username.vljde
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'StringField' object has no attribute 'vljde'
2024-10-12 12:08:50,019 INFO: Microblog startup [in C:\Users\deadg\microblog\app\__init__.py:48]
